### ISSUE TITLE
Looks like AXIOS is no longer working

### ISSUE THREAD

**Issue by sourman** [EcomGraduates/loom-downloader#2]
PS C:\Users\User\workspace\loom-downloader> node download.js --url https://www.loom.com/share/9bce00d279924e8fb3c701ab53bcdb35?sid=cd52528c-ee61-44d6-a9ab-bf7f1072db5c

C:\Users\User\workspace\loom-downloader\node_modules\axios\dist\node\axios.cjs:1913
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 404
    at settle (C:\Users\User\workspace\loom-downloader\node_modules\axios\dist\node\axios.cjs:1913:12)
    at Unzip.handleStreamEnd (C:\Users\User\workspace\loom-downloader\node_modules\axios\dist\node\axios.cjs:2995:11)
    at Unzip.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },

Node.js v18.13.0

**Comment by EcomGraduates** [comment]
this should be resolved now thank you for reporting it
